[package]
name = "comm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comm_core = {path = "./CommunicationCore"}
eframe = "0.21.3"
egui = "0.21.0"
# chrono = "0.4.24"